# Generated by Django 4.1.1 on 2022-10-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
