# Generated by Django 4.1.1 on 2022-10-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_categories_listings_user_rating_watchlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.listings'),
            preserve_default=False,
        ),
    ]
