# Generated by Django 4.1.1 on 2022-10-10 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_startingbid_alter_listings_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='startingBid',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
