# Generated by Django 4.1.1 on 2022-10-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listings_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.bids'),
        ),
    ]
